site_info = [
    { "url": "https://whc.unesco.org/en/list/937", "name": "Península Valdés", "article": None },
    { "url": "https://whc.unesco.org/en/list/154", "name": "Great Barrier Reef", "article": None },
    { "url": "https://whc.unesco.org/en/list/186", "name": "Lord Howe Island Group", "article": None },
    { "url": "https://whc.unesco.org/en/list/578", "name": "Shark Bay, Western Australia", "article": None },
    { "url": "https://whc.unesco.org/en/list/577", "name": "Heard and McDonald Islands", "article": None },
    { "url": "https://whc.unesco.org/en/list/629", "name": "Macquarie Island", "article": None },
    { "url": "https://whc.unesco.org/en/list/1369", "name": "Ningaloo Coast", "article": None },
    { "url": "https://whc.unesco.org/en/list/798", "name": "The Sundarbans", "article": None },
    { "url": "https://whc.unesco.org/en/list/764", "name": "Belize Barrier Reef Reserve System", "article": None },
    { "url": "https://whc.unesco.org/en/list/1000", "name": "Brazilian Atlantic Islands: Fernando de Noronha and Atol das Rocas Reserves", "article": "https://www.unesco.org/en/articles/brazilian-youth-joins-unesco-environmental-dna-sampling-fernando-de-noronha?hub=66910" },
    { "url": "https://whc.unesco.org/en/list/72", "name": "Kluane / Wrangell-St. Elias / Glacier Bay / Tatshenshini-Alsek", "article": None },
    { "url": "https://whc.unesco.org/en/list/1216", "name": "Malpelo Fauna and Flora Sanctuary", "article": None },
    { "url": "https://whc.unesco.org/en/list/820", "name": "Cocos Island National Park", "article": None },
    { "url": "https://whc.unesco.org/en/list/928", "name": "Area de Conservación Guanacaste", "article": None },
    { "url": "https://whc.unesco.org/en/list/1314", "name": "Wadden Sea", "article": None },
    { "url": "https://whc.unesco.org/en/list/1", "name": "Galápagos Islands", "article": None },
    { "url": "https://whc.unesco.org/en/list/898", "name": "High Coast / Kvarken Archipelago", "article": None },
    { "url": "https://whc.unesco.org/en/list/258", "name": "Gulf of Porto: Calanche of Piana, Gulf of Girolata, Scandola Reserve", "article": "https://www.unesco.org/en/articles/schoolchildren-support-scientists-gulf-porto-france-part-unescos-environmental-dna-initiative?hub=66910" },
    { "url": "https://whc.unesco.org/en/list/1115", "name": "Lagoons of New Caledonia: Reef Diversity and Associated Ecosystems", "article": "https://www.unesco.org/en/articles/associations-and-management-committees-are-taking-part-unescos-edna-campaign-lagoons-new-caledonia?hub=66910" },
    { "url": "https://whc.unesco.org/en/list/1603", "name": "French Austral Lands and Seas", "article": "https://www.unesco.org/en/articles/young-scientists-sample-seawater-search-vulnerable-marine-species-french-austral-lands-and-seas?hub=66910" },
    { "url": "https://whc.unesco.org/en/list/1314", "name": "Wadden Sea", "article": None },
    { "url": "https://whc.unesco.org/en/list/1267", "name": "Surtsey", "article": None },
    { "url": "https://whc.unesco.org/en/list/452", "name": "Sundarbans National Park", "article": "https://www.unesco.org/en/articles/school-aged-pupils-and-university-students-join-unesco-environmental-dna-sampling-sundarbans?hub=66910" },
    { "url": "https://whc.unesco.org/en/list/609", "name": "Komodo National Park", "article": None },
    { "url": "https://whc.unesco.org/en/list/608", "name": "Ujung Kulon National Park", "article": None },
    { "url": "https://whc.unesco.org/en/list/1193", "name": "Shiretoko", "article": None },
    { "url": "https://whc.unesco.org/en/list/1362", "name": "Ogasawara Islands", "article": None },
    { "url": "https://whc.unesco.org/en/list/1325", "name": "Phoenix Islands Protected Area", "article": None },
    { "url": "https://whc.unesco.org/en/list/506", "name": "Banc d'Arguin National Park", "article": "https://www.unesco.org/en/articles/students-participate-environmental-dna-sampling-banc-darguin-national-park-mauritania?hub=66910" },
    { "url": "https://whc.unesco.org/en/list/410", "name": "Sian Ka'an", "article": None },
    { "url": "https://whc.unesco.org/en/list/554", "name": "Whale Sanctuary of El Vizcaino", "article": None },
    { "url": "https://whc.unesco.org/en/list/1182", "name": "Islands and Protected Areas of the Gulf of California", "article": None },
    { "url": "https://whc.unesco.org/en/list/1510", "name": "Archipiélago de Revillagigedo", "article": None },
    { "url": "https://whc.unesco.org/en/list/1314", "name": "Wadden Sea", "article": None },
    { "url": "https://whc.unesco.org/en/list/877", "name": "New Zealand Sub-Antarctic Islands", "article": None },
    { "url": "https://whc.unesco.org/en/list/1195", "name": "West Norwegian Fjords – Geirangerfjord and Nærøyfjord", "article": None },
    { "url": "https://whc.unesco.org/en/list/1386", "name": "Rock Islands Southern Lagoon", "article": None },
    { "url": "https://whc.unesco.org/en/list/1138", "name": "Coiba National Park and its Special Zone of Marine Protection", "article": "https://www.unesco.org/en/articles/children-become-edna-citizen-scientists-coiba-national-park-panama?hub=66910" },
    { "url": "https://whc.unesco.org/en/list/653", "name": "Tubbataha Reefs Natural Park", "article": "https://www.unesco.org/en/articles/volunteers-join-unesco-edna-sampling-tubbataha-reefs-philippines?hub=66910" },
    { "url": "https://whc.unesco.org/en/list/652", "name": "Puerto-Princesa Subterranean River National Park", "article": None },
    { "url": "https://whc.unesco.org/en/list/1023", "name": "Natural System of Wrangel Island Reserve", "article": None },
    { "url": "https://whc.unesco.org/en/list/185", "name": "Aldabra Atoll", "article": "https://www.unesco.org/en/articles/seychellois-school-children-collect-edna-samples-during-trip-lifetime-aldabra-atoll?hub=66910" },
    { "url": "https://whc.unesco.org/en/list/854", "name": "East Rennell", "article": None },
    { "url": "https://whc.unesco.org/en/list/914", "name": "iSimangaliso Wetland Park", "article": "https://www.unesco.org/en/articles/school-children-rural-areas-south-africa-join-edna-sampling-isimangaliso-wetland-park?hub=66910" },
    { "url": "https://whc.unesco.org/en/list/417", "name": "Ibiza, Biodiversity and Culture", "article": None },
    { "url": "https://whc.unesco.org/en/list/262", "name": "Sanganeb Marine National Park and Dungonab Bay – Mukkawar Island Marine National Park", "article": "https://www.unesco.org/en/articles/students-sudan-join-unesco-edna-sampling-red-sea?hub=66910" },
    { "url": "https://whc.unesco.org/en/list/898", "name": "High Coast / Kvarken Archipelago", "article": None },
    { "url": "https://whc.unesco.org/en/list/387", "name": "St Kilda", "article": None },
    { "url": "https://whc.unesco.org/en/list/740", "name": "Gough and Inaccessible Islands", "article": None },
    { "url": "https://whc.unesco.org/en/list/76", "name": "Everglades National Park", "article": "https://www.unesco.org/en/articles/high-school-students-join-unesco-edna-campaign-everglades-national-park?hub=66910" },
    { "url": "https://whc.unesco.org/en/list/72", "name": "Kluane / Wrangell-St. Elias / Glacier Bay / Tatshenshini-Alsek", "article": None },
    { "url": "https://whc.unesco.org/en/list/1326", "name": "Papahānaumokuākea", "article": None },
    { "url": "https://whc.unesco.org/en/list/672", "name": "Ha Long Bay", "article": None },
    { "url": "https://whc.unesco.org/en/list/1263", "name": "Socotra Archipelago", "article": None }
]