site_info = [
    { "url": "https://whc.unesco.org/en/list/937", "name": "Península Valdés" },
    { "url": "https://whc.unesco.org/en/list/154", "name": "Great Barrier Reef" },
    { "url": "https://whc.unesco.org/en/list/186", "name": "Lord Howe Island Group" },
    { "url": "https://whc.unesco.org/en/list/578", "name": "Shark Bay, Western Australia" },
    { "url": "https://whc.unesco.org/en/list/577", "name": "Heard and McDonald Islands" },
    { "url": "https://whc.unesco.org/en/list/629", "name": "Macquarie Island" },
    { "url": "https://whc.unesco.org/en/list/1369", "name": "Ningaloo Coast" },
    { "url": "https://whc.unesco.org/en/list/798", "name": "The Sundarbans" },
    { "url": "https://whc.unesco.org/en/list/764", "name": "Belize Barrier Reef Reserve System" },
    { "url": "https://whc.unesco.org/en/list/1000", "name": "Brazilian Atlantic Islands: Fernando de Noronha and Atol das Rocas Reserves" },
    { "url": "https://whc.unesco.org/en/list/72", "name": "Kluane / Wrangell-St. Elias / Glacier Bay / Tatshenshini-Alsek" },
    { "url": "https://whc.unesco.org/en/list/1216", "name": "Malpelo Fauna and Flora Sanctuary" },
    { "url": "https://whc.unesco.org/en/list/820", "name": "Cocos Island National Park" },
    { "url": "https://whc.unesco.org/en/list/928", "name": "Area de Conservación Guanacaste" },
    { "url": "https://whc.unesco.org/en/list/1314", "name": "Wadden Sea" },
    { "url": "https://whc.unesco.org/en/list/1", "name": "Galápagos Islands" },
    { "url": "https://whc.unesco.org/en/list/898", "name": "High Coast / Kvarken Archipelago" },
    { "url": "https://whc.unesco.org/en/list/258", "name": "Gulf of Porto: Calanche of Piana, Gulf of Girolata, Scandola Reserve" },
    { "url": "https://whc.unesco.org/en/list/1115", "name": "Lagoons of New Caledonia: Reef Diversity and Associated Ecosystems" },
    { "url": "https://whc.unesco.org/en/list/1603", "name": "French Austral Lands and Seas" },
    { "url": "https://whc.unesco.org/en/list/1314", "name": "Wadden Sea" },
    { "url": "https://whc.unesco.org/en/list/1267", "name": "Surtsey" },
    { "url": "https://whc.unesco.org/en/list/452", "name": "Sundarbans National Park" },
    { "url": "https://whc.unesco.org/en/list/609", "name": "Komodo National Park" },
    { "url": "https://whc.unesco.org/en/list/608", "name": "Ujung Kulon National Park" },
    { "url": "https://whc.unesco.org/en/list/1193", "name": "Shiretoko" },
    { "url": "https://whc.unesco.org/en/list/1362", "name": "Ogasawara Islands" },
    { "url": "https://whc.unesco.org/en/list/1325", "name": "Phoenix Islands Protected Area" },
    { "url": "https://whc.unesco.org/en/list/506", "name": "Banc d'Arguin National Park" },
    { "url": "https://whc.unesco.org/en/list/410", "name": "Sian Ka'an" },
    { "url": "https://whc.unesco.org/en/list/554", "name": "Whale Sanctuary of El Vizcaino" },
    { "url": "https://whc.unesco.org/en/list/1182", "name": "Islands and Protected Areas of the Gulf of California" },
    { "url": "https://whc.unesco.org/en/list/1510", "name": "Archipiélago de Revillagigedo" },
    { "url": "https://whc.unesco.org/en/list/1314", "name": "Wadden Sea" },
    { "url": "https://whc.unesco.org/en/list/877", "name": "New Zealand Sub-Antarctic Islands" },
    { "url": "https://whc.unesco.org/en/list/1195", "name": "West Norwegian Fjords – Geirangerfjord and Nærøyfjord" },
    { "url": "https://whc.unesco.org/en/list/1386", "name": "Rock Islands Southern Lagoon" },
    { "url": "https://whc.unesco.org/en/list/1138", "name": "Coiba National Park and its Special Zone of Marine Protection" },
    { "url": "https://whc.unesco.org/en/list/653", "name": "Tubbataha Reefs Natural Park" },
    { "url": "https://whc.unesco.org/en/list/652", "name": "Puerto-Princesa Subterranean River National Park" },
    { "url": "https://whc.unesco.org/en/list/1023", "name": "Natural System of Wrangel Island Reserve" },
    { "url": "https://whc.unesco.org/en/list/185", "name": "Aldabra Atoll" },
    { "url": "https://whc.unesco.org/en/list/854", "name": "East Rennell" },
    { "url": "https://whc.unesco.org/en/list/914", "name": "iSimangaliso Wetland Park" },
    { "url": "https://whc.unesco.org/en/list/417", "name": "Ibiza, Biodiversity and Culture" },
    { "url": "https://whc.unesco.org/en/list/262", "name": "Sanganeb Marine National Park and Dungonab Bay – Mukkawar Island Marine National Park" },
    { "url": "https://whc.unesco.org/en/list/898", "name": "High Coast / Kvarken Archipelago" },
    { "url": "https://whc.unesco.org/en/list/387", "name": "St Kilda" },
    { "url": "https://whc.unesco.org/en/list/740", "name": "Gough and Inaccessible Islands" },
    { "url": "https://whc.unesco.org/en/list/76", "name": "Everglades National Park" },
    { "url": "https://whc.unesco.org/en/list/72", "name": "Kluane / Wrangell-St. Elias / Glacier Bay / Tatshenshini-Alsek" },
    { "url": "https://whc.unesco.org/en/list/1326", "name": "Papahānaumokuākea" },
    { "url": "https://whc.unesco.org/en/list/672", "name": "Ha Long Bay" },
    { "url": "https://whc.unesco.org/en/list/1263", "name": "Socotra Archipelago" }
]